#!/bin/bash
# usage: backup-tsohost
#
# perform incremental backups using rsync.  See rsync-backup for details
# of how the backup is performed.

from_dir="$tsohost:/home/f36enrwgolmi"

bdisk=/mnt/data
if [[ ! -e "$bdisk" ]]; then
    echo "backup disk is missing: $bdisk"
    exit 1
fi

backup_dir=${bdisk}/esheldon/backups/tsohost
name=tsohost

rsync-backup $from_dir $backup_dir $name
