#!/bin/bash
# usage: backup-rivendell
#
# perform incremental backups using rsync.  See rsync-backup for details
# of how the backup is performed.

exclude_list=~/git/misc/backup_excludes/rivendell
if [[ ! -e $exclude_list ]]; then
    echo "exclude list ${exclude_list} missing"
    exit 1
fi
from_dir=$HOME

bdisk=/mnt/data
if [[ ! -e "$bdisk" ]]; then
    echo "backup disk is missing: $bdisk"
    exit 1
fi

backup_dir=${bdisk}/esheldon/backups/rivendell
name=rivendell

rsync-backup -e $exclude_list $from_dir $backup_dir $name
