#!/bin/bash
# Calculate some statistics for the indicated columns.  The data come
# in on stdin
#
# usage:
#     colstats c1 c2 ...  < file
#     cat file | colstats c1 c2 ...
#
# example:
#
#> colstats 1 2 < test.dat 
#      nrow      total        min        max        std       mean        err
#      2379     436788         77        400   59.01414   183.6015   1.209926
#      2379     513872         98        276   44.32997   162.8348   1.743632


function usage_and_exit {
    echo "usage: colstats [-3] [-n {ncols}] col1 col2 ..."
    echo "  send -3 to show 2 sigma errors"
    echo "  send -n {ncols} to only look at rows with than many entries"
    echo "  send data on stdin"
    exit 1
}
if [[ $# -lt 1 ]]; then
    usage_and_exit
fi

ncols="notgiven"

show_3sig="no"

while getopts "n:3" Option
  do
  case $Option in
      n)  ncols=$OPTARG ;;
      3)   show_3sig="yes";;
      [?]) usage_and_exit;; 
  esac
done
shift $(($OPTIND - 1))

if [[ $ncols == "notgiven" ]]; then
    check=""
else
    check="(NF==$ncols)"
fi

script=""
begin=""
dostats=""
prnt=""
i=1
for col; do 
    begin="$begin
    minvals[$col]=9999e50;
    maxvals[$col]=-9999e50;
    "

    script="$script
    sum[$col] += \$$col;
    sum2[$col] += \$$col*\$$col;
    if (\$$col > maxvals[$col]) maxvals[$col]=\$$col;
    if (\$$col < minvals[$col]) minvals[$col]=\$$col;
    "

    dostats="$dostats
    mn[$col]=sum[$col]/NR;
    mn2[$col]=sum2[$col]/NR;
    std[$col]=sqrt( (mn2[$col] - mn[$col]*mn[$col]));
    "
    if [[ $show_3sig == "yes" ]]; then
        dostats="$dostats
        err[$col]=3.0*sqrt( (mn2[$col] - mn[$col]*mn[$col])/NR);
        "
    else
        dostats="$dostats 
        err[$col]=sqrt( (mn2[$col] - mn[$col]*mn[$col])/NR);
        "
    fi

    prnt="${prnt}
    printf \"%10d %10.7g %10.7g %10.7g %12.7g %12.7g %12.7g\\n\", NR, sum[$col], minvals[$col], maxvals[$col], mn[$col], err[$col], std[$col]"

    i=$((i = i+1))
done

if [[ $show_3sig == "yes" ]]; then
    errstr="3*err"
else
    errstr="err"
fi
awkscript="BEGIN {
    $begin
} $check {
    $script
} END {
    $dostats
    printf \"%10s %10s %10s %10s %12s %12s %12s\\n\", \"nrow\", \"total\", \"min\", \"max\", \"mean\", \"$errstr\", \"std\"
    $prnt
}"

#echo "$awkscript"
#exit
awk "$awkscript" < /dev/stdin
