#!/bin/bash

print_memory() {
    # left=$(free -h | awk '/^Mem:/ {print $7}')
    # perc=$(free | awk '/^Mem:/ {printf "%.0f", $7/$2*100}')
    # echo -ne "mem ${left} ${perc}%"
    left=$(free -h | awk '/^Mem:/ {print $7"/"$2}')
    echo -ne "mem ${left}"
}

print_power_old() {
	capacity=$(cat /sys/class/power_supply/BAT0/capacity 2> /dev/null) || exit
	status=$(cat /sys/class/power_supply/BAT0/status)

	if [ "$capacity" -ge 75 ]; then
		color="#00ff00"
	elif [ "$capacity" -ge 50 ]; then
		color="#ffffff"
	elif [ "$capacity" -ge 25 ]; then
		color="#ffff00"
	else
		color="#ff0000"
		warn="❗"
	fi

	[ -z $warn ] && warn=" "

	[ "$status" = "Charging" ] && color="#ffffff"

	# printf "<span color='%s'>%s%s%s</span>\n" "$color" "$(echo "$status" | sed -e "s/,//;s/Discharging/🔋/;s/Not charging/🛑/;s/Charging/🔌/;s/Unknown/♻️/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"
	printf "%s%s%s" "$(echo "$status" | sed -e "s/,//;s/Discharging/🔋/;s/Not charging/🛑/;s/Charging/🔌/;s/Unknown/♻️/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"

}
print_power() {
	capacity=$(cat /sys/class/power_supply/BAT0/capacity 2> /dev/null) || exit
	status=$(cat /sys/class/power_supply/BAT0/status)

    tm=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | egrep "time" | cut -d : -f 2 | xargs)

	[ "$status" = "Charging" ] && color="#ffffff"

	printf "%s %s %s" "$(echo "$capacity" | sed -e 's/$/%/')" "$(echo "$status" | sed -e "s/,//;s/Discharging/↓/;s/Not charging/X/;s/Charging/↑/;s/Unknown/?/;s/Full/⚫/;s/ 0*/ /g;s/ :/ /g")" "$tm"

}

print_wifiqual() {
    wifiessid="$(/sbin/iwconfig 2>/dev/null | grep ESSID | cut -d: -f2)"
    wifiawk="$(echo $wifiessid | awk -F',' '{gsub(/"/, "", $1); print $1}')"
    wificut="$(echo $wifiawk | cut -d' ' -f1)"
    echo -ne "${wificut}"
}

print_hddfree() {

    dft=$(df -Ph | awk '/nvme0n1p2/ {print $4"/"$2}')
    if [[ $dft == "" ]]; then
        dft=$(df -Ph | awk '/sda1/ {print $4"/"$2}')
        if [[ $dft == "" ]]; then
            dft=$(df -Ph | awk '/sdb1/ {print $4"/"$2}')
        fi
    fi
    echo -ne "hdd $dft"
}

print_datetime() {
    datetime="$(date "+%D %I:%M")"
    echo -ne "${datetime}"
}

# print_load() {
#     load=$(uptime | awk -F ',' '{print $(NF-2)""$(NF-1)""$(NF)}'| sed 's/  load average:/load/')
#     echo -ne "${load}"
# }

while true; do

    # load=$(uptime | awk '{print $10,$11,$12}' | awk -F ', ' '{print $1, $2, $3}')
    text="$(print_memory) | $(print_hddfree)"
    # text="$(print_memory) | $(print_hddfree)"

    power=$(print_power)
    if [[ $power != "" ]]; then
        text="${text} | bat ${power}"
    fi
    text="${text} | $(print_datetime)"
    xsetroot -name "${text}"

    sleep 1
done
