#!/bin/bash

function usage_and_exit {
    echo "usage:
  lsf-incsub-flist [options] flist

options:
    -n NJOBS_MAX  Maximum number of jobs in queue, default $max_jobs
    -p time between polls of wq status when we are at max allowed
       jobs, default $poll_time
    -s time to sleep between individual submissions when trying to
       catch up to the max number of jobs, default $sleep_time second
    -f force submission of jobs even if the {jobfile}.submitted 
       sentinel file exists
"
    exit 1
}

function count_jobs {
    njobs=$(bjobs | grep -v FROM_HOST | wc -l )
    echo "$njobs"
}

function get_diffjobs {
    njobs=$(bjobs | grep -v FROM_HOST | wc -l )
    ((diffjobs = max_jobs - njobs))
    echo "$njobs $diffjobs"
}


# time to wait after we have filled our limit
poll_time=30
sleep_time=0.2
max_jobs=1000
force="false"

if [ $# -lt 1 ]; then
    usage_and_exit
fi
while getopts "n:s:p:f" Option
do
    case $Option in
        n) max_jobs=$OPTARG ;;
        s) sleep_time=$OPTARG ;;
        p) poll_time=$OPTARG ;;
        f) force="true" ;;
        [?]) usage_and_exit ;;
    esac
done
shift $(($OPTIND - 1))

flist=$1
nfiles=$(cat $flist | wc -l)

i=1

read njobs diffjobs <<<$(get_diffjobs)

cat $flist | while read file_full; do

    file=$(basename $file_full)
    dir=$(dirname $file_full)
    pushd $dir &> /dev/null

    perc=$(echo "scale=0; 100*$i/$nfiles" | bc)

    logf="${file}.submitted"

    if [[ $force == "true" || ! -e $logf ]]; then

        if [[ $diffjobs -le 0 ]]; then
            sleep $poll_time
            read njobs diffjobs <<<$(get_diffjobs)
            while [[ $diffjobs -le 0 ]]; do
                sleep $poll_time
                read njobs diffjobs <<<$(get_diffjobs)
            done
            echo "Found $njobs jobs  diffjobs: $diffjobs"
        fi

        dt=`date +"%T"`
        echo "    submitting $file $dt $i/$nfiles (${perc}%)"
        bsub < "$file"

        if [[ $? != 0 ]]; then
            echo "Error submitting job through bsub: $?"
            exit 1
        fi

        touch "$logf"

        ((diffjobs -= 1))
        sleep $sleep_time

    fi

    popd &> /dev/null
    let "i += 1"

done
